.TH vocr 1
.SH NAME
vocr \- a simple utility for performing optical character recognition
on images and PDFs
.SH SYNOPSIS
vocr [\-v] [\-f] [\-p] [\-a [accurate|fast]] [\-i [no|tab]] [\-l [lang]] [-L] [files]
.SH DESCRIPTION
vocr is a simple utility for performing optical character recognition
(OCR) on images and PDFs. It prints any text found in the specified
files to stdout.  vocr relies on, and derives its names from, the
Vision framework (v for [V]ision).
.SH OPTIONS
.TP
.B \-a [accurate|fast]
Specifies the ocr algorithm to use, either "accurate" or "fast". By
default vocr uses the "accurate" algorithm, but the "fast" algorithm
may be useful when recognizing text in non\-English languages, such
as German.
.TP
.B \-i [no|tab]
If \-i is specified with the "no" option, vocr will not attempt to indent
any text that is OCR\'ed.  If \-i is specified with the "tab" option, vocr
will indent using tabs instead of spaces (by default vocr indents using
spaces).
.TP
.B \-p
When OCR\'ing a PDF, tells vocr to insert a page break (^L) at the end
of each page.
.TP
.B \-f
For PDFs, forces vocr to perform ocr.  By default, if a PDF already contains
a text representation of a given page, vocr will output that text.
.TP
.B \-l [lang]
If \-l is specified, on MacOSX 11.x (BigSur) and newer, vocr will ask the
Vision framework to recognize the text in the specified language.  The
supported language options are: "de" (German), "en" (English), "fr"
(French), "it" (Italian), "pt" (Portuguese), "es" (Spanish), "zh"
(Chinese).
.TP
.B \-v
Enables verbose mode \- vocr will print out informational and error
messages.
.TP
.B \-L
Lists available languages.
.SH PLATFORMS
vorc has been tested on MacOSX 11.x (BigSur),  12.x (Monterey), and
14.x (Sonoma) on M1 and x86_64.  It should also work on MacOSX 10.15 
(Catalina) x86_64.
.SH HISTORY
vocr was written by Sriranga Veeraraghavan <ranga@calalum.org>.
